version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: php_app
    volumes:
      - ./public:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet: